const db = require("../database");
const jwt = require('jsonwebtoken');


// function decoded
function jwtDecoded(reqCookie) {
  // jwt decode
  const token = reqCookie;
  var id;
  jwt.verify(token, process.env.SECRET_STRING, (err, decoded) => {
    if (err) {
      return res.status(401).json({ message: 'Failed to authenticate token' });
    }

    // The decoded payload is available in the 'decoded' object
    id = decoded.id;
  });
  return id;
}

exports.uploadText = async (req, res) => {
  const { text } = req.body;

  if (!text) {
    const response = res.status(400).send({
      status: "Gagal",
      message: "Semua ketentuan wajib diisi!",
    });
    return response;
  }

  if (text.length > 2000) {
    const response = res.status(400).send({
      status: "Gagal",
      message: "Panjang teks tidak boleh lebih dari 2000 karakter!",
    });
    return response;
  }

  id = jwtDecoded(req.cookies.jwt);

  await db.promise().query(`INSERT INTO uploads (raw_file, processed_file, result_file, user_id) VALUES('${text}', '-', 'generated by ai', ${id})`);

  const response = res.status(201).send({
    status: "Sukses",
    message: req.body.text,
  });

  return response;
};
